### ISSUE TITLE
Flagging Error

### ISSUE THREAD

**Issue by Daniel4-Scratch** [snap-cloud/SnapSite#97] opened 2020-10-01 02:38 UTC
1. What browsers show this problem? I guess any
2. Please share an example project (if possible). ![Screen Shot 2020-10-01 at 12.11.20 pm|690x347](https://snap-forums-data.s3.dualstack.us-west-2.amazonaws.com/optimized/2X/0/085b2c05aec6bcd6097d45aab3b5ad9250b1e8db_2_690x347.png) 
3. Describes the steps to reproduce this issue. Flag [this](https://snap.berkeley.edu/project?user=jose.espinell&project=Animation%20project%201_Jose%20Espinell) project
4. What does Snap<em>!</em> currently do? show an error message
5. What should Snap<em>!</em> do instead? flag the project/add it to the flagged collection.

I marked the project as inappropriate as it of swearing and it won't flag. Also is this because someone else flagged it and it was already added to the flag collection and it can't do it?
*Originally on the Snap Forums https://forum.snap.berkeley.edu/t/flagging-error/3379/3*

**Comment by bromagosa** [comment] 2020-10-07 10:22
Close as duplicate of #80

**Closed by bromagosa** 2020-10-07 10:22 UTC
